theme: minima
title: Il Quaderno della Prof
description: Questo sito Ã¨ creato e gestito da Lucia Capurri e i contenuti presenti si intendono liberamente disponibili con licenza CC-BY-NC, a scopo didattico.
lang: it
header_pages:
  - about.md
